name: Create release

on:
  push:
    branches:
      - 'release/*'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.package-info.outputs.version }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get package info
        id: package-info
        uses: codex-team/action-nodejs-package-info@v1.1

      - name: Create Tag
        uses: actions/github-script@v6
        env:
          TAG: v${{ steps.package-info.outputs.version }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.package-info.outputs.version }}",
              sha: context.sha
            })

  release_windows:
    needs: [create_tag]
    runs-on: windows-2019

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable-cache
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Run build app
        run: |
          yarn build:app

      - name: Run package electron app for windows
        run: |
          yarn package:electron-app:win

      - name: Release windows build
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.create_tag.outputs.package_version }}
          files: |
            ./release/out/Nimble Electron Boilerplate Setup ${{ needs.create_tag.outputs.package_version }}.exe

  release_macos:
    needs: [create_tag]
    runs-on: macOS-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable-cache
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Run build app
        run: |
          yarn build:app

      - name: Run package electron app for macOS
        run: |
          yarn package:electron-app:mac

      - name: Release macOS build
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.create_tag.outputs.package_version }}
          files: |
            ./release/out/Nimble Electron Boilerplate-${{ needs.create_tag.outputs.package_version }}-arm64-mac.zip
            ./release/out/Nimble Electron Boilerplate-${{ needs.create_tag.outputs.package_version }}-arm64.dmg
            ./release/out/Nimble Electron Boilerplate-${{ needs.create_tag.outputs.package_version }}-mac.zip
            ./release/out/Nimble Electron Boilerplate-${{ needs.create_tag.outputs.package_version }}.dmg
            ./docs/Help-guide.docx
